name: Run E2E Tests server

on: [push]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: api

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Use Bun.sh
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun run test:e2e
        working-directory: ./apps/server

        env:
          NODE_ENV: development
          JWT_SECRET: testing
          DATABASE_URL: "postgresql://docker:docker@localhost:5432/api"
          API_BASE_URL: http://localhost:3001
          AUTH_REDIRECT_URL: http://localhost:3000
          GITHUB_OAUTH_CLIENT_ID: oauthclientid
          GITHUB_OAUTH_SECRET_ID: oauthsecretid
          GITHUB_OAUTH_REDIRECT_URL: http://localhost:3000/auth/github/callback
          GOOGLE_OAUTH_CLIENT_ID: oauthclientid
          GOOGLE_OAUTH_SECRET_ID: oauthsecretid
          GOOGLE_OAUTH_REDIRECT_URL: http://localhost:3000/auth/google/callback
          LINKEDIN_OAUTH_CLIENT_ID: oauthclientid
          LINKEDIN_OAUTH_SECRET_ID: oauthsecretid
          LINKEDIN_OAUTH_REDIRECT_URL: http://localhost:3000/auth/linkedin/callback
          NEXT_PUBLIC_API_BASE_URL: http://localhost:3001
          NEXT_PUBLIC_API_MOCKING: true
